spring.application.name: api-auth

server:
  port: 8480
  servlet:
    context-path: /ifa
 

spring:
  datasource:
    #url: jdbc:mysql://pbplena.cx6ag23ztkle.ap-northeast-2.rds.amazonaws.com:3306/worktimemanagement?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    #username: worktime
    #password: Worktimemanagement1! 
    url: jdbc:mysql://db-2o9bg.cdb.ntruss.com:3306/ifclient?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: ifclient
    password: if!@client34
    driver-class-name: com.mysql.cj.jdbc.Driver 
    
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
#  session:
#    redis:
#      flush-mode: on-save
#      namespace: spring:session
#    timeout: 3600s
#    store-type: redis
  
#  redis:
#    lettuce:
#      pool:
#        max-active: 10
#        max-idle: 10
#        min-idle: 2
#    host: 192.168.111.12
#    port: 6379
#    password: isu!!2019
    
  redis:
    url: 192.168.111.12
    port: 6379
    password: isu!!2019
  main:
    allow-bean-definition-overriding: true
    
security:
  oauth2:
    jwt:
      signkey: iSuSystEmW0rkT1meM@n@gemEnTServ1c2
      
      
logging:
  level:
    root: warn
  org.springframework:
    web: warn
    security: info
    boot: info
  org.hibernate:
    SQL: warn
  com.isu.ifa: debug
  
    
  